name = "LicenseCheck"
uuid = "726dbf0d-6eb6-41af-b36c-cd770e0f00cc"
authors = ["Eric P. Hanson"]
version = "0.1.0"

[deps]
licensecheck_jll = "4ecb348a-8b88-51ea-b912-4c460483ee91"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
